name: Build and publish Docker image to quay.io

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build_push_image:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to quay.io through Robot account
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.QUAY_ROBOT_USER }}
          password: ${{ secrets.QUAY_ROBOT_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ${{ secrets.QUAY_ROBOT_USER }}/ipmi-exporter
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
